# rokae:
#   joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50
#   arm_controller:
#     type: position_controllers/JointTrajectoryController
#     joints:
#       - xmate_joint_1
#       - xmate_joint_2
#       - xmate_joint_3
#       - xmate_joint_4
#       - xmate_joint_5
#       - xmate_joint_6
#       - xmate_joint_7
#       - xmate_joint_8

# rokae/gazebo_ros_control/pid_gains:
#        xmate_joint_1:   {p: 100, i: 0.01, d: 10.0}
#        xmate_joint_2:   {p: 100, i: 0.01, d: 10.0}
#        xmate_joint_3:   {p: 100, i: 0.01, d: 10.0}
#        xmate_joint_4:   {p: 100, i: 0.01, d: 10.0}
#        xmate_joint_5:   {p: 100, i: 0.01, d: 10.0}
#        xmate_joint_6:   {p: 100, i: 0.01, d: 10.0}
#        xmate_joint_7:  {p: 100, i: 0.01, d: 10.0}
#        xmate_joint_8:  {p: 100, i: 0.01, d: 10.0}


rokae:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - xmate_joint_1
      - xmate_joint_2
      - xmate_joint_3
      - xmate_joint_4
      - xmate_joint_5
      - xmate_joint_6
      - xmate_joint_7

    gains:
      xmate_joint_1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      xmate_joint_2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      xmate_joint_3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      xmate_joint_4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      xmate_joint_5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      xmate_joint_6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      xmate_joint_7:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}


  hand_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      # - taotong_tool_joint
      - tool_taotong

    gains:

      tool_taotong:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      # taotong_tool_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}


    # gains:
    #   xmate_joint_1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_7:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   tool_taotong:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}



    # gains:
    #   xmate_joint_1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   xmate_joint_7:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    #   tool_taotong:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      # taotong_tool_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
