# rokae:
#   # Publish all joint states -----------------------------------
#   joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 300  
  
#   # Position Controllers ---------------------------------------
#   group1_controller:
#     type: effort_controllers/JointPositionController
#     joints:
#         - xmate_joint_1
#         - xmate_joint_2
#         - xmate_joint_3
#         - xmate_joint_4
#         - xmate_joint_5
#         - xmate_joint_6
#         - xmate_joint_7
#   group2_controller:
#     type: effort_controllers/JointPositionController
#     joints:
#        - joint: xmate_joint_8


# rokae/gazebo_ros_control/pid_gains:
#    xmate_joint_1: {p: 5000.0, i: 0.0, d: 100.0}
#    xmate_joint_2: {p: 5000.0, i: 0.0, d: 100.0}
#    xmate_joint_3: {p: 5000.0, i: 0.0, d: 100.0}
#    xmate_joint_4: {p: 5000.0, i: 0.0, d: 100.0}
#    xmate_joint_5: {p: 5000.0, i: 0.0, d: 100.0}
#    xmate_joint_6: {p: 5000.0, i: 0.0, d: 100.0}
#    xmate_joint_7: {p: 5000.0, i: 0.0, d: 100.0}
#    xmate_joint_8: {p: 5000.0, i: 0.0, d: 100.0}



rokae:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 300  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: xmate_joint_1
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: xmate_joint_2
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: xmate_joint_3
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: xmate_joint_4
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: xmate_joint_5
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: xmate_joint_6
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: xmate_joint_7
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: xmate_joint_8
    pid: {p: 5000.0, i: 0.01, d: 100.0}

#gazebo_ros_control/pid_gains:
  #lf_rot_1: {p: 5000.0, i: 0.0, d: 100.0}
  #lf_rot_2: {p: 5000.0, i: 0.0, d: 100.0}
  #lf_rot_3: {p: 5000.0, i: 0.0, d: 100.0}
  #rf_rot_1: {p: 5000.0, i: 0.0, d: 100.0}
  #rf_rot_2: {p: 5000.0, i: 0.0, d: 100.0}
  #rf_rot_3: {p: 5000.0, i: 0.0, d: 100.0}
  #lb_rot_1: {p: 5000.0, i: 0.0, d: 100.0}
  #lb_rot_2: {p: 5000.0, i: 0.0, d: 100.0}
  #lb_rot_3: {p: 5000.0, i: 0.0, d: 100.0}
  #rb_rot_1: {p: 5000.0, i: 0.0, d: 100.0}
  #rb_rot_2: {p: 5000.0, i: 0.0, d: 100.0}
  #rb_rot_3: {p: 5000.0, i: 0.0, d: 100.0}

